# Website name at top left
title: Joseph Nagel

# Author name at the bottom
author: Joseph Nagel

# Avatar picture at the top
avatar: /assets/images/Photo.jpg

# Social media links at the bottom
social-network-links:
  email: JosephBNagel@gmail.com
  github: joseph-nagel

# Short description
description: This website contains projects related to machine learning, neural networks, computer vision, generative AI and Bayesian inference.

# Links in the navigation bar
navbar-links:
  Home: /
  Blog: /blog/
  ML intros:
    - Boltzmann machines: /2025/11/07/rbm.html
    # - Energy-based models: /2025/10/28/boltzmann.html
    - Diffusion models: /2024/12/12/ddpm.html
    - VAE: /2024/12/11/vae.html
    - GP models: /2024/12/10/gp.html
    - Physics-informed neural nets: /2024/12/09/pinn.html
    - Attention: /2024/12/08/attention.html
    - Contrastive learning: /2024/12/07/contrastive-learning.html
    - Adversarial ML: /2024/12/06/adversarial-ml.html
  ML projects: /projects/
  CV: /cv/
  Publications: /publications/

# Timezone
timezone: Europe/Berlin

# Include items
include:
  - _pages

# Build settings
# theme: beautiful-jekyll-theme
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jemoji
